// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// compute_AR_stat
double compute_AR_stat(const arma::vec& b, const arma::mat& y_res, const arma::mat& Y_res, const arma::mat& Pz, const arma::mat& Mz, int H, int T_ess, int d_AR);
RcppExport SEXP _spiv_compute_AR_stat(SEXP bSEXP, SEXP y_resSEXP, SEXP Y_resSEXP, SEXP PzSEXP, SEXP MzSEXP, SEXP HSEXP, SEXP T_essSEXP, SEXP d_ARSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type b(bSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type y_res(y_resSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Y_res(Y_resSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Pz(PzSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Mz(MzSEXP);
    Rcpp::traits::input_parameter< int >::type H(HSEXP);
    Rcpp::traits::input_parameter< int >::type T_ess(T_essSEXP);
    Rcpp::traits::input_parameter< int >::type d_AR(d_ARSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_AR_stat(b, y_res, Y_res, Pz, Mz, H, T_ess, d_AR));
    return rcpp_result_gen;
END_RCPP
}
// compute_KLM_stat
double compute_KLM_stat(const arma::vec& b, const arma::mat& y_res, const arma::mat& Y_res, const arma::mat& v_res, const arma::mat& Mz, const arma::mat& Pz, const arma::mat& R, int H, int T_ess, int d_K);
RcppExport SEXP _spiv_compute_KLM_stat(SEXP bSEXP, SEXP y_resSEXP, SEXP Y_resSEXP, SEXP v_resSEXP, SEXP MzSEXP, SEXP PzSEXP, SEXP RSEXP, SEXP HSEXP, SEXP T_essSEXP, SEXP d_KSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type b(bSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type y_res(y_resSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Y_res(Y_resSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type v_res(v_resSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Mz(MzSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Pz(PzSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type R(RSEXP);
    Rcpp::traits::input_parameter< int >::type H(HSEXP);
    Rcpp::traits::input_parameter< int >::type T_ess(T_essSEXP);
    Rcpp::traits::input_parameter< int >::type d_K(d_KSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_KLM_stat(b, y_res, Y_res, v_res, Mz, Pz, R, H, T_ess, d_K));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_spiv_compute_AR_stat", (DL_FUNC) &_spiv_compute_AR_stat, 8},
    {"_spiv_compute_KLM_stat", (DL_FUNC) &_spiv_compute_KLM_stat, 10},
    {NULL, NULL, 0}
};

RcppExport void R_init_spiv(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
