# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

compute_AR_stat <- function(b, y_res, Y_res, Pz, Mz, H, T_ess, d_AR) {
    .Call(`_spiv_compute_AR_stat`, b, y_res, Y_res, Pz, Mz, H, T_ess, d_AR)
}

compute_KLM_stat <- function(b, y_res, Y_res, v_res, Mz, Pz, R, H, T_ess, d_K) {
    .Call(`_spiv_compute_KLM_stat`, b, y_res, Y_res, v_res, Mz, Pz, R, H, T_ess, d_K)
}

compute_robust_grid <- function(grid_values, start_index, end_index, y_res, Y_res, v_res, Pz, Mz, R, H, T_ess, d, critical_value, is_klm) {
    .Call(`_spiv_compute_robust_grid`, grid_values, start_index, end_index, y_res, Y_res, v_res, Pz, Mz, R, H, T_ess, d, critical_value, is_klm)
}

